### ISSUE TITLE
bug: Buttons are not responsive on home page

### ISSUE THREAD

**Issue by KubiixD** [Global-Tags/Panel#7] opened 2024-09-19 19:20 UTC
![Screenshot_2024-09-19-17-14-34-71_d365b52accad0f47adbc08c16219827d](https://github.com/user-attachments/assets/d96b4b1f-0483-4117-806c-ae481d468c43)
We love CSS 😍😍

**Comment by RappyTV** [comment] 2024-09-19 20:49
duplicate of #6

**Closed by RappyTV** 2024-09-19 20:49 UTC
Labels: duplicate
